"""
merge_stations_with_crime.py


Merges crime incidences with the nearest subway stations.
"""
import pandas as pd
import geopandas as gpd

INPUT_DATA_CRIME = "/Users/arjunshanmugam/Documents/GitHub/econ1660-final/data/raw/processed_crime_data_2019.csv"
INPUT_DATA_SUBWAY = "/Users/arjunshanmugam/Documents/GitHub/econ1660-final/data/raw/body.csv"

crime_gdf = pd.read_csv(INPUT_DATA_CRIME)[['Latitude', 'Longitude', 'INCIDENT_DATE', 'TYP_DESC']]
crime_types_to_include = """OTHER CRIMES (IN PROGRESS): VIOL ORDER PROTECT/OUTSIDE
BURGLARY (IN PROGRESS): COMMERCIAL/TRANSIT
BURGLARY (IN PROGRESS): OTHER
VEHICLE ACCIDENT: PERSON PINNED
ROBBERY (IN PROGRESS): BANK/TRANSIT
INVESTIGATE/POSSIBLE CRIME: SUSP VEHICLE/TRANSIT
OTHER CRIMES (IN PROGRESS): GRAFFITI VANDALISM
DISPUTE: FIREARM/TRANSIT
ROBBERY (IN PROGRESS): BANK
ASSAULT (IN PROGRESS): KNIFE/CHILD ABUSE
ASSAULT (IN PROGRESS): OTHER/OUTSIDE
UNUSUAL INCIDENT: TRANSIT
OTHER CRIMES (IN PROGRESS): HARASSMENT/INSIDE
OTHER CRIMES (IN PROGRESS): OTHER/TRANSIT
INVESTIGATE/POSSIBLE CRIME: SUSP PERSON/OUTSIDE (PROWLER)
EXPLOSIVE DEVICE OR THREAT: POSSIBLE BOMB/TRANSIT
INVESTIGATE/POSSIBLE CRIME: NARCO SALES/TRANSIT
ALARMS: COMMERCIAL/BURGLARY
ROBBERY (IN PROGRESS): COMMERCIAL/TRANSIT
ASSAULT (IN PROGRESS): OTHER/FAMILY
SHOT SPOTTER
INVESTIGATE/POSSIBLE CRIME: SUSP PERSON/LTD ACC HWY
ALARMS: RESIDENTIAL/BURGLARY
VEHICLE ACCIDENT: PERSON PINNED/LTD ACC HWY
BURGLARY (IN PROGRESS): OTHER/TRANSIT
DISORDERLY: PERSON/OUTSIDE
DISORDERLY: GROUP/OUTSIDE
LARCENY (IN PROGRESS): VEHICLE/INSIDE
OTHER CRIMES (IN PROGRESS): TRESPASS/OUTSIDE
DISPUTE: KNIFE/INSIDE
DISPUTE: FIREARM/INSIDE
ASSAULT (IN PROGRESS): WEAPON/TRANSIT
OTHER CRIMES (IN PROGRESS): TRESPASS/TRANSIT
OTHER CRIMES (IN PROGRESS): VIOL ORDER PROTECT/FAMILY
ALARMS: BANK/HOLDUP
BURGLARY (IN PROGRESS): COMMERCIAL
OTHER CRIMES (IN PROGRESS): CRIM MISCHIEF/INSIDE
ROBBERY (IN PROGRESS): OTHER/LTD ACC HWY
ASSAULT (IN PROGRESS): KNIFE/LTD ACC HWY
INVESTIGATE/POSSIBLE CRIME: KNIFE/INSIDE
ASSAULT (IN PROGRESS): SHOTS/CHILD
OTHER CRIMES (IN PROGRESS): GRAFF VANDALISM/LTD ACC HWY
DISPUTE: FIREARM/FAMILY
INVESTIGATE/POSSIBLE CRIME: FIREARM/LTD ACC HWY
ASSAULT (IN PROGRESS): OTHER/TRANSIT
ASSAULT (IN PROGRESS): WEAPON/CHILD
LARCENY (IN PROGRESS): OTHER/OUTSIDE
PO/SECURITY HOLDING SUSPECT: UNKNOWN/TRANSIT
INVESTIGATE/POSSIBLE CRIME: KNIFE/LTD ACC HWY
OTHER CRIMES (IN PROGRESS): GRAFF VANDALISM/TRANSIT
OTHER CRIMES (IN PROGRESS): OTHER/OUTSIDE
DISPUTE: FIREARM/OUTSIDE
OTHER CRIMES (IN PROGRESS): VIOL ORDER PROTECT/TRANSIT
DISPUTE: OUTSIDE
INVESTIGATE/POSSIBLE CRIME: FIREARM/TRANSIT
OTHER CRIMES (IN PROGRESS): VIOL ORDER PROTECT/INSIDE
LARCENY (IN PROGRESS): FROM PERSON/TRANSIT
BURGLARY (IN PROGRESS): RESIDENCE
DISPUTE: KNIFE/LTD ACC HWY
INVESTIGATE/POSSIBLE CRIME: NARCO SALES/LTD ACC HWY
OTHER CRIMES (IN PROGRESS): CRIM MISCHIEF/LTD ACC HWY
INVESTIGATE/POSSIBLE CRIME: SUSP PERSON/TRANSIT
ASSAULT (IN PROGRESS): WEAPON/INSIDE
ASSAULT (IN PROGRESS): SHOTS/TRANSIT
ALARMS: BANK/TRANSIT
DISPUTE: VIOL ORDER PROTECT/OUTSIDE
LARCENY (IN PROGRESS): OTHER/LTD ACC HWY
DISPUTE: KNIFE/FAMILY
INVESTIGATE/POSSIBLE CRIME: FIREARM/OUTSIDE
LARCENY (IN PROGRESS): FROM PERSON/LTD ACC HWY
ROBBERY (IN PROGRESS): OTHER/INSIDE
LARCENY (IN PROGRESS): VEHICLE/LTD ACC HWY
ALARMS: BANK/BURGLARY
INVESTIGATE/POSSIBLE CRIME: CALLS FOR HELP/INSIDE
ALARMS: COMMERCIAL/TRANSIT
INVESTIGATE/POSSIBLE CRIME: KNIFE/OUTSIDE
ROBBERY (IN PROGRESS): COMMERCIAL
ASSAULT (IN PROGRESS): KNIFE/OUTSIDE
OTHER CRIMES (IN PROGRESS): OTHER/INSIDE
INVESTIGATE/POSSIBLE CRIME: OTHER/TRANSIT
ASSAULT (IN PROGRESS): OTHER/LTD ACC HWY
ROBBERY (IN PROGRESS): OTHER/OUTSIDE
ALARMS: COMMERCIAL/HOLDUP
DISORDERLY: PERSON/TRANSIT
LARCENY (IN PROGRESS): FROM PERSON/OUTSIDE
INVESTIGATE/POSSIBLE CRIME: OTHER/INSIDE
ASSAULT (IN PROGRESS): KNIFE/INSIDE
DISPUTE: KNIFE/TRANSIT
ASSAULT (IN PROGRESS): SHOTS/OUTSIDE
STATION INSPECTION BY TRANSIT BUREAU PERSONNEL
ASSAULT (IN PROGRESS): KNIFE/TRANSIT
OTHER CRIMES (IN PROGRESS): HARASSMENT/LTD ACC HWY
INVESTIGATE/POSSIBLE CRIME: CALLS FOR HELP/TRANSIT
ALARMS: OTHER/BURGLARY
ASSAULT (IN PROGRESS): WEAPON/FAMILY
INVESTIGATE/POSSIBLE CRIME: KNIFE/TRANSIT
DISPUTE: TRANSIT
EXPLOSIVE DEVICE OR THREAT: POSSIBLE BOMB/LTD ACC HWY
OTHER CRIMES (IN PROGRESS): HARASSMENT/TRANSIT
ASSAULT (IN PROGRESS): OTHER/CHILD ABUSE
INVESTIGATE/POSSIBLE CRIME: CALLS FOR HELP/OUTSIDE
ASSAULT (IN PROGRESS): OTHER/INSIDE
PO/SECURITY HOLDING SUSPECT: UNKNOWN/OUTSIDE
LARCENY (IN PROGRESS): VEHICLE/OUTSIDE
INVESTIGATE/POSSIBLE CRIME: SHOTS FIRED/INSIDE
INVESTIGATE/POSSIBLE CRIME: CALLS FOR HELP/LTD ACC HWY
ROBBERY (IN PROGRESS): OTHER/TRANSIT
ROBBERY (IN PROGRESS): RESIDENCE
OTHER CRIMES (IN PROGRESS): HARASSMENT/OUTSIDE
INVESTIGATE/POSSIBLE CRIME: SUSP PERSON/INSIDE (PROWLER)
DISPUTE: VIOL ORDER PROTECT/TRANSIT
ASSAULT (IN PROGRESS): SHOTS/INSIDE
PO/SECURITY HOLDING SUSPECT: UNIFORM/OUTSIDE
EXPLOSIVE DEVICE OR THREAT: POSSIBLE BOMB
INVESTIGATE/POSSIBLE CRIME: FIREARM/INSIDE
PO/SECURITY HOLDING SUSPECT: UNIFORM/TRANSIT
DISPUTE: KNIFE/OUTSIDE
LARCENY (IN PROGRESS): FROM PERSON/INSIDE
INVESTIGATE/POSSIBLE CRIME: OTHER/OUTSIDE
OTHER CRIMES (IN PROGRESS): OTHER/LTD ACC HWY
ASSAULT (IN PROGRESS): WEAPON/LTD ACC HWY
DISPUTE: VIOL ORDER PROTECT/FAMILY
INVESTIGATE/POSSIBLE CRIME: POSSIBLE CHILD ABUSE
ASSAULT (IN PROGRESS): SHOTS/FAMILY
INVESTIGATE/POSSIBLE CRIME: SHOTS FIRED/OUTSIDE
LARCENY (IN PROGRESS): OTHER/TRANSIT
PO/SECURITY HOLDING SUSPECT: UNKNOWN/LTD ACC HWY
VEHICLE ACCIDENT: HIT BY AUTO/LTD ACC HWY
DISPUTE: VIOL ORDER PROTECT/LTD ACC HWY
INVESTIGATE/POSSIBLE CRIME: SHOTS FIRED/TRANSIT
INVESTIGATE/POSSIBLE CRIME: SERIOUS OTHER/LTD ACC HWY
OTHER CRIMES (IN PROGRESS): TRESPASS/INSIDE
ASSAULT (IN PROGRESS): WEAPON/OUTSIDE
INVESTIGATE/POSSIBLE CRIME: SERIOUS OTHER/TRANSIT
LARCENY (IN PROGRESS): OTHER/INSIDE
DISPUTE: VIOL ORDER PROTECT/INSIDE
OTHER CRIMES (IN PROGRESS): VIOL ORDER PROTECT/LTD ACC HWY
INVESTIGATE/POSSIBLE CRIME: SHOTS/LTD ACC HWY
ASSAULT (IN PROGRESS): KNIFE/FAMILY
OTHER CRIMES (IN PROGRESS): CRIM MISCHIEF/TRANSIT
OTHER CRIMES (IN PROGRESS): CRIM MISCHIEF/OUTSIDE
INVESTIGATE/POSSIBLE CRIME: SERIOUS/OTHER
""".split("\n")
crime_gdf = crime_gdf.loc[crime_gdf['TYP_DESC'].isin(crime_types_to_include), :].reset_index(drop=True)
crime_gdf.loc[:, 'INCIDENT_DATE'] = pd.to_datetime(crime_gdf['INCIDENT_DATE'])
crime_gdf = (gpd.GeoDataFrame(crime_gdf,
                              geometry=gpd.points_from_xy(crime_gdf['Longitude'],
                                                          crime_gdf['Latitude']))
             .set_crs("EPSG:4326"))
crime_gdf = crime_gdf.rename(columns={'INCIDENT_DATE': 'Date'})

subway_gdf = pd.read_csv(INPUT_DATA_SUBWAY)[['gtfs_longitude', 'gtfs_latitude', 'date']]
subway_gdf.loc[:, 'date'] = pd.to_datetime(subway_gdf['date'])
subway_gdf = (gpd.GeoDataFrame(subway_gdf,
                               geometry=gpd.points_from_xy(subway_gdf['gtfs_longitude'],
                                                           subway_gdf['gtfs_latitude']))
              .set_crs("EPSG:4326"))
subway_gdf = subway_gdf.rename(columns={'date': 'Date'})

# Join crimes with the nearest subway station.
print(subway_gdf['Date'])
print(crime_gdf['Date'])
subway_gdf = subway_gdf.loc[subway_gdf['Date'].isin(crime_gdf['Date']), :]
crime_gdf = crime_gdf.loc[crime_gdf['Date'].isin(subway_gdf['Date']), :]
shards = {k: d for k, d in subway_gdf.groupby('Date')}
gdf = crime_gdf.groupby('Date').apply(lambda d: gpd.sjoin_nearest(d, shards[d['Date'].values[0]]))

gdf.to_csv("~/Desktop/merge_test.csv")